call "C:\Program Files\USGS\ModelMuse4\bin\ModelMonitor.exe" -m D:\bin\RMODFLOW\MODFLOW-NWT\bin\MODFLOW-NWT_64.exe -n C:\Virtual-D\prj\2020\bch_education-evenings-2020\2020_iah-belgium_abitm\a-brief-introduction-to-modelmuse_data-based-modelling\model\data-based.nam
Start Notepad.exe C:\Virtual-D\prj\2020\bch_education-evenings-2020\2020_iah-belgium_abitm\a-brief-introduction-to-modelmuse_data-based-modelling\model\data-based.lst
pause
