call "C:\Program Files\USGS\ModelMuse4\bin\ModelMonitor.exe" -m C:\Virtual-D\prj\2020\bch_education-evenings-2020\2020_iah-belgium_abitm\a-brief-introduction-to-modelmuse_software\modflow\modflow-2005-1.12.exe -n C:\Virtual-D\prj\2020\bch_education-evenings-2020\2020_iah-belgium_abitm\a-brief-introduction-to-modelmuse_sketch-a-model\model\sketch.nam
Start Notepad.exe C:\Virtual-D\prj\2020\bch_education-evenings-2020\2020_iah-belgium_abitm\a-brief-introduction-to-modelmuse_sketch-a-model\model\sketch.lst
call RunModpath.bat
pause
